[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
	let g:deoplete#enable_at_startup = 1
	let g:deoplete#enable_ignore_case = 1
"	inoremap <expr><tab> pumvisible() ? "\<C-n>" :
"        \ neosnippet#expandable_or_jumpable() ?
"        \    "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
'''

[[plugins]]
repo = 'tyru/eskk.vim'
hook_add = '''
	let g:eskk#large_dictionary={
	    \   'path': "~/.skk-dic/SKK-JISYO-utf8.L",
	    \   'sorted': 1,
	    \   'encoding': 'utf-8',
	    \}
'''

[[plugins]]
repo = 'vim-jp/autofmt'

[[plugins]]
repo = 'Shougo/neco-vim'

[[plugins]]
repo = 'Shougo/neco-syntax'

[[plugins]]
repo = 'ujihisa/neco-look'

